### ISSUE TITLE
ROFLPlayer causing client to repair

### ISSUE THREAD

**Issue by fraxiinus** [andrew1421lee/ROFL-Player#19]
Mirror of this particular comment: https://github.com/leeanchu/ROFL-Player/issues/17#issuecomment-489897895

**Comment by ghost** [comment]
Hey there !

Here is the content of the Default file I used :
`{"Name":"Default","TargetPath":"C:\\Riot Games\\League of Legends\\Game\\League of Legends.exe","StartFolder":"C:\\Riot Games\\League of Legends","PatchVersion":"9.9.272.4950","AllowUpdates":true,"IsDefault":true,"ModifiedDate":"2019-05-07T17:55:44.2212944-04:00"}`

I don't think the problem is coming from your ROLF player, but it's either coming from the path used or from Riot messing up their files.

The replay does open and works perfectly fine. But it's not detected by league director. And the next time I open the client, it will need a 3min repair. (Replays work without a problem when launched from the client in my match history)

I did contact Riot support today and here is their answer : 
![Screenshot_1](https://user-images.githubusercontent.com/50350165/57340756-7ca77500-7137-11e9-8386-63486fe90e84.png)

I don't know how much the support's answer is reliable, but they said replays shouldn't work anymore outside of the profile.

**Comment by fraxiinus** [comment]
So it seems that there are some serious issues going on with the replay system in general. Like you said, this issue is probably not coming from ROFLPlayer. I'll keep a look out on any other developments.

**Comment by fraxiinus** [comment]
Client crashes should now be fixed in patch 9.11
I will keep this issue open in case the crashes continues.

**Comment by ghost** [comment]
Hey there !
I tested it again, and the client still had to do a repair after I opened it :/

**Comment by fraxiinus** [comment]
Can you try setting the start folder in your exec file to `C:\\Riot Games\\League of Legends\\Game`? Client repairing is a sign that the replay is not being launched from the same directory as the game.

**Comment by ghost** [comment]
Hey again !
I tried it right away :

![Screenshot_1](https://user-images.githubusercontent.com/50350165/59291524-641d0400-8c7b-11e9-937e-05db5214d511.png)

I changed it in the json file as you told me and you can see the change reflected into the app.
But I still got the repair.
PS: I didn't update to 0.9b if that can be useful for you.

**Comment by fraxiinus** [comment]
Updating to 0.9b shouldn't do much to fix this problem. You can try though.

Maybe it's because of where ROFLPlayer is being run from?

**Comment by ghost** [comment]
Where do you suggest I run it from?

**Comment by fraxiinus** [comment]
I put ROFLPlayer in my replay folder in My Documents.

**Comment by ghost** [comment]
It didn't fix the problem for me.
I also moved to the new version.

I'm pretty surprised you didn't encounter this bug

**Comment by fraxiinus** [comment]
Yeah this problem is still stumping me. Are you able to 100% reproduce the bug? If you can, can you share what you do to have the bug occur? Is there maybe a pattern of how you close the game and start another?

**Comment by ghost** [comment]
Yes, I can confirm that the bug occurs 100% of the time. I also showed the app to a friend and he's encountering the same thing.

To reproduce : 
Play a rofl file with ROFL Player. I close them by going into the setting then I click on exit. I then see the "are you sure you want to exit" as if you want to go afk in a game. Pretty normal.

Then on my next opening of the client (either by opening it directly, or closing it and open it if it was open while using rofl player), it will do a very small repair that takes about 3min.
It only happens when I open the client, not when I launch a game or play another rofl.

If you want, I can show you in a screenshare on discord when we both have time.

**Comment by fraxiinus** [comment]
Hoorah! I'm able to reproduce the bug.

This bug is happening because the game client is still trying to look for the RADS directories even though Riot stopped using RADS. I'll be able to fix this soon!

**Comment by ghost** [comment]
Hooray !
It was a pain, Glad to know it's gonna get fixed soon !

And thanks a lot for your hard work !

**Comment by fraxiinus** [comment]
Tested and Resolved in 5f40819

Changes:
* ROFLPlayer will now properly set the ProcessStartInfo instead of using the shortcut hack to play replays.
* ROFLPlayer now uses correct launch arguments when playing replays

These changes will be pushed into the next release

**Comment by ghost** [comment]
Awesome !

I'll be waiting for the next release

**Comment by fraxiinus** [comment]
Fix released in https://github.com/leeanchu/ROFL-Player/releases/tag/1.0
